////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online AlbionVersion
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albion_Direct
{
	/* Internal type: ObfuscatedName */
	public enum RefactoredName
	{
		ValuesPlaceholder
	}
	
	public static class RefactoredNameExtensions
	{
		public static ObfuscatedName ToInternal(this RefactoredName instance)
		{
			return (ObfuscatedName)instance;
		}
		
		public static RefactoredName ToWrapped(this ObfuscatedName instance)
		{
			return (RefactoredName)instance;
		}
	}
}