////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online AlbionVersion
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

using UnityEngine;

using Albion.Common.Time;

using NUnit.Framework;

namespace Merlin.API.Direct.Tests
{
	/* Internal type: ObfuscatedName */
	[TestFixture]
	public class RefactoredNameTests
	{
		#region Conversion
		
		TestsPlaceholder
		
		#endregion
	}
}